version: 0.0
os: linux
files:
  - source: /app.zip
    destination: /home/ubuntu/app
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 180
      runas: ubuntu
  Install:
    - location: scripts/install.sh
      timeout: 180
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 180
      runas: ubuntu
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 180
      runas: ubuntu
