name: Deploy to AWS via CodeDeploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2  # Change to your AWS region

      # Step 3: Archive the codebase
      - name: Zip the codebase
        run: zip -r app.zip . -x "*.git*"

      # Step 4: Upload to S3
      - name: Upload artifact to S3
        run: |
          aws s3 cp app.zip s3://rhmbucket/app.zip

# Step 5: Deploy using CodeDeploy
      - name: Deploy to EC2 using CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name RHM \
            --deployment-group-name production \
            --s3-location bucket=rhmbucket,bundleType=zip,key=app.zip
